### ISSUE TITLE
Starknet Issue

### ISSUE THREAD

**Issue by 0xJust1** [munris-vlad/wallet-checker#1]
Hello, Starknet Issue, any idea ? 

ReferenceError: fetch is not defined

Fetch > starknetapiurl > starkscan.stellate.sh ? 

Im trying to find something, but i dont know node.js :/

**Comment by munris-vlad** [comment]
update your nodejs version to 18+

**Comment by 0xJust1** [comment]
> update your nodejs version to 18+

Thanks
